#!/usr/bin/env bash
set -euo pipefail

NETWORK="${NETWORK:-etl-demo}"
POSTGRES_NAME="${POSTGRES_NAME:-demo-postgres}"
MARIADB_NAME="${MARIADB_NAME:-demo-mariadb}"
MONGO_NAME="${MONGO_NAME:-demo-mongo}"
POSTGRES_PORT="${POSTGRES_PORT:-5432}"
MARIADB_PORT="${MARIADB_PORT:-3307}"
MONGO_PORT="${MONGO_PORT:-27018}"
RECREATE=0

if [[ "${1:-}" == "--recreate" ]]; then
  RECREATE=1
fi

if ! command -v docker >/dev/null 2>&1; then
  echo "docker command not found." >&2
  exit 1
fi

if ! docker network inspect "${NETWORK}" >/dev/null 2>&1; then
  docker network create "${NETWORK}" >/dev/null
fi

if docker ps -a --format '{{.Names}}' | grep -qx "${POSTGRES_NAME}"; then
  if [[ "${RECREATE}" -eq 1 ]]; then
    docker rm -f "${POSTGRES_NAME}" >/dev/null
  else
    docker start "${POSTGRES_NAME}" >/dev/null || true
  fi
fi

if ! docker ps -a --format '{{.Names}}' | grep -qx "${POSTGRES_NAME}"; then
  docker run -d --name "${POSTGRES_NAME}" --network "${NETWORK}" \
    -e POSTGRES_USER=postgres \
    -e POSTGRES_PASSWORD=postgres \
    -e POSTGRES_DB=srcdb \
    -p "${POSTGRES_PORT}:5432" \
    postgres:16 >/dev/null
fi

if docker ps -a --format '{{.Names}}' | grep -qx "${MARIADB_NAME}"; then
  if [[ "${RECREATE}" -eq 1 ]]; then
    docker rm -f "${MARIADB_NAME}" >/dev/null
  else
    docker start "${MARIADB_NAME}" >/dev/null || true
  fi
fi

if ! docker ps -a --format '{{.Names}}' | grep -qx "${MARIADB_NAME}"; then
  docker run -d --name "${MARIADB_NAME}" --network "${NETWORK}" \
    -e MARIADB_ROOT_PASSWORD=root \
    -e MARIADB_DATABASE=dstdb \
    -e MARIADB_USER=etl \
    -e MARIADB_PASSWORD=etlpass \
    -p "${MARIADB_PORT}:3306" \
    mariadb:11 >/dev/null
fi

if docker ps -a --format '{{.Names}}' | grep -qx "${MONGO_NAME}"; then
  if [[ "${RECREATE}" -eq 1 ]]; then
    docker rm -f "${MONGO_NAME}" >/dev/null
  else
    docker start "${MONGO_NAME}" >/dev/null || true
  fi
fi

if ! docker ps -a --format '{{.Names}}' | grep -qx "${MONGO_NAME}"; then
  docker run -d --name "${MONGO_NAME}" --network "${NETWORK}" \
    -e MONGO_INITDB_ROOT_USERNAME=admin \
    -e MONGO_INITDB_ROOT_PASSWORD=admin \
    -p "${MONGO_PORT}:27017" \
    mongo:7 >/dev/null
fi

pg_port_mapped="$(docker port "${POSTGRES_NAME}" 5432/tcp | head -n1 | awk -F: '{print $NF}')"
maria_port_mapped="$(docker port "${MARIADB_NAME}" 3306/tcp | head -n1 | awk -F: '{print $NF}')"
mongo_port_mapped="$(docker port "${MONGO_NAME}" 27017/tcp | head -n1 | awk -F: '{print $NF}')"

PORTS_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.demo_ports"
cat >"${PORTS_FILE}" <<EOF
# Auto-generated by docker_up.sh — do not edit manually
POSTGRES_PORT=${pg_port_mapped:-${POSTGRES_PORT}}
MARIADB_PORT=${maria_port_mapped:-${MARIADB_PORT}}
MONGO_PORT=${mongo_port_mapped:-${MONGO_PORT}}
EOF

echo "Docker demo databases are running:"
echo "- PostgreSQL: ${POSTGRES_NAME} on 127.0.0.1:${pg_port_mapped:-unknown}"
echo "- MariaDB: ${MARIADB_NAME} on 127.0.0.1:${maria_port_mapped:-unknown}"
echo "- MongoDB: ${MONGO_NAME} on 127.0.0.1:${mongo_port_mapped:-unknown}"
echo "Port file written to: ${PORTS_FILE}"
